# Netlify configuration file

[build]
  command = "npm run build"
  publish = ".next"
  
# Include Next.js specific build settings
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configure routing for SPA and dynamic routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin", "user"]}
  
[[redirects]]
  from = "/api/*"
  to = "https://api.landingpad-digital.com/:splat"
  status = 200
  force = true

# Configure headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Function configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"