FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install nodemon for development
RUN npm install -g nodemon

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Set environment variables
ENV NODE_ENV=development
ENV PORT=3000

# Expose the application port
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "run", "dev"]