global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files to load
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend metrics
  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 5s
    scrape_timeout: 4s

  # Backend metrics (to be implemented)
  - job_name: 'backend'
    metrics_path: '/api/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['backend:5000']
    scrape_interval: 5s
    scrape_timeout: 4s

  # Node Exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']