import { apiHelpers } from './api';
import { AIContentPrompt, AIContentResult, AISuggestion } from '@/components/ai/types';
import { generateId } from './utils';

/**
 * AI Service for generating content
 */
export const aiService = {
  /**
   * Generate content based on a prompt
   */
  generateContent: async (prompt: AIContentPrompt): Promise<AIContentResult> => {
    try {
      const response = await apiHelpers.post('/ai/generate', prompt);
      return response.result;
    } catch (error) {
      console.error('Error generating AI content:', error);
      
      // Fallback fake response for development
      return {
        id: generateId(),
        type: prompt.type,
        prompt: prompt.prompt,
        content: getFallbackContent(prompt),
        alternativeContents: [
          getAlternativeFallbackContent(prompt, 1),
          getAlternativeFallbackContent(prompt, 2),
        ],
        timestamp: Date.now(),
      };
    }
  },
  
  /**
   * Get suggestions based on element type and context
   */
  getSuggestions: async (elementType: string, context?: Record<string, any>): Promise<AISuggestion[]> => {
    try {
      const response = await apiHelpers.post('/ai/suggestions', { elementType, context });
      return response.suggestions;
    } catch (error) {
      console.error('Error getting AI suggestions:', error);
      
      // Fallback fake suggestions for development
      return getFallbackSuggestions(elementType);
    }
  },
  
  /**
   * Get alternative content for an existing content
   */
  getAlternatives: async (contentId: string, count: number = 3): Promise<string[]> => {
    try {
      const response = await apiHelpers.get(`/ai/alternatives/${contentId}`, { count });
      return response.alternatives;
    } catch (error) {
      console.error('Error getting AI alternatives:', error);
      
      // Fallback fake alternatives for development
      return [
        'Alternative content option 1 - this is a placeholder for development.',
        'Alternative content option 2 - this would come from the AI service.',
        'Alternative content option 3 - customize this to your needs.',
      ];
    }
  },
  
  /**
   * Improve content with AI assistance
   */
  improveContent: async (content: string, direction: string): Promise<string> => {
    try {
      const response = await apiHelpers.post('/ai/improve', { content, direction });
      return response.improved;
    } catch (error) {
      console.error('Error improving content with AI:', error);
      
      // Fallback fake improved content for development
      return `${content} (${direction} version - AI improved placeholder)`;
    }
  },
};

// Helper functions for development fallbacks
function getFallbackContent(prompt: AIContentPrompt): string {
  switch (prompt.type) {
    case 'headline':
      return 'Compelling Headline for Your Amazing Product';
    case 'paragraph':
      return 'This is a placeholder paragraph that would normally be generated by our AI service. It would be relevant to your prompt and provide high-quality content for your website. In a production environment, this would be replaced with actual AI-generated content based on your specific inputs and requirements.';
    case 'tagline':
      return 'Innovation Simplified | Results Amplified';
    case 'cta':
      return 'Start Your Free Trial Today';
    case 'features':
      return 'Easy to use, Powerful analytics, 24/7 support';
    case 'testimonial':
      return 'This product has completely transformed our workflow. We\'ve seen a 40% increase in productivity since implementation!';
    case 'seo-title':
      return 'Best Solutions for Modern Businesses | Your Brand';
    case 'seo-description':
      return 'Discover how our innovative solutions can help your business grow. Expert service, proven results, and dedicated support.';
    default:
      return `AI-generated content for "${prompt.prompt}" would appear here.`;
  }
}

function getAlternativeFallbackContent(prompt: AIContentPrompt, version: number): string {
  switch (prompt.type) {
    case 'headline':
      return version === 1 
        ? 'Transform Your Business with Our Revolutionary Solution' 
        : 'Unlock Your Potential: The Ultimate Business Tool';
    case 'paragraph':
      return `This is alternative paragraph version ${version}. In production, this would be a different AI-generated paragraph based on your prompt. Each alternative would provide different wording, tone, or approach while still addressing your core requirements.`;
    case 'tagline':
      return version === 1 
        ? 'Simplify. Amplify. Succeed.' 
        : 'Your Vision, Our Technology';
    default:
      return `Alternative ${version} for "${prompt.prompt}" would appear here.`;
  }
}

function getFallbackSuggestions(elementType: string): AISuggestion[] {
  switch (elementType) {
    case 'hero':
      return [
        {
          id: generateId(),
          type: 'headline',
          content: 'Transform Your Online Presence with Our Powerful Platform',
          context: 'hero heading',
        },
        {
          id: generateId(),
          type: 'paragraph',
          content: 'Create stunning websites in minutes, not months. Our AI-powered platform takes care of the design, content, and optimization so you can focus on growing your business.',
          context: 'hero subheading',
        },
        {
          id: generateId(),
          type: 'cta',
          content: 'Start Building for Free',
          context: 'hero button',
        },
      ];
    case 'features':
      return [
        {
          id: generateId(),
          type: 'headline',
          content: 'Features That Set Us Apart',
          context: 'features heading',
        },
        {
          id: generateId(),
          type: 'features',
          content: 'AI-Powered Design, Drag-and-Drop Editor, SEO Optimization',
          context: 'feature list',
        },
      ];
    case 'testimonials':
      return [
        {
          id: generateId(),
          type: 'headline',
          content: 'What Our Customers Are Saying',
          context: 'testimonials heading',
        },
        {
          id: generateId(),
          type: 'testimonial',
          content: 'Landing Pad Digital has revolutionized how we approach our web presence. In just two days, we had a beautiful website that perfectly represents our brand.',
          context: 'customer testimonial',
        },
      ];
    default:
      return [
        {
          id: generateId(),
          type: 'headline',
          content: 'AI-Generated Headline Suggestion',
          context: 'general heading',
        },
        {
          id: generateId(),
          type: 'paragraph',
          content: 'This is a placeholder for AI-generated content suggestions. In production, these suggestions would be tailored to your specific element type and context.',
          context: 'general content',
        },
      ];
  }
}
