name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Disable parallel testing for now to focus on making tests pass
    strategy:
      fail-fast: true
      matrix:
        containers: [1] # Run in a single container
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create test directories
        run: bash .github/workflows/create-test-dirs.sh
        
      - name: Setup PostgreSQL for Cypress
        run: bash .github/workflows/setup-cypress-db.sh
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install root dependencies
        run: npm install
        
      - name: Set up Cypress environment
        run: bash .github/workflows/setup-cypress.sh
        
      - name: Copy test env file to backend
        run: cp .github/workflows/test.env backend/.env
    
      - name: Copy test env file to frontend
        run: cp .github/workflows/test.env frontend/.env.local
        
      - name: Fix next-auth imports
        run: bash .github/workflows/fix-next-auth.sh
        
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Use start-server-and-test to run both frontend and backend
          start: npm run dev
          wait-on: 'http://localhost:3000' # Waits for frontend
          wait-on-timeout: 180 # Give servers more time to start
          # Disable recording for now
          record: false
          parallel: false
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY || '' }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}